--- #YAML:1.0
name:                Lingua-Identify
version:             0.19
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Class::Factory::Util:          1.6
    Text::Affixes:                 0.04
    Text::ExtractWords:            0.08
    Text::Ngram:                   0.03
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
