# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Lingua-Identify
version:      0.10
version_from: lib/Lingua/Identify.pm
installdirs:  site
requires:
    Class::Factory::Util:          1.6
    Text::Affixes:                 0.04
    Text::ExtractWords:            0.08
    Text::Ngram:                   0.03

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
