--- #YAML:1.0
name:               Lingua-Identify
version:            0.22
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::Factory::Util:  1.6
    Text::Affixes:        0.04
    Text::ExtractWords:   0.08
    Text::Ngram:          0.03
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
